# mongodb 连接
mongodb:
    host: '127.0.0.1'
    port: 27017
    user: 'root'
    passwd: 'root'
    db: 'test'
    table: 'test'

# mysql 连接
mysqlContent:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    passwd: "root"
    db: "test"